export const PUBLISHERS_MAP = [
  { label: "Marvel", id: "31" },
  { label: "DC Comics", id: "10" },
  { label: "Image", id: "4091" },
  { label: "Dark Horse", id: "34" },
  { label: "IDW Publishing", id: "1637" },
  { label: "Boom! Studios", id: "1873" },
  { label: "Dynamite Entertainment", id: "1868" },
  { label: "Vertigo", id: "18" },
  { label: "Valiant", id: "2005" },
  { label: "Aftershock Comics", id: "6929" },
  { label: "Titan Comics", id: "2264" },
  { label: "Oni Press", id: "172" },
  { label: "Top Cow", id: "161" },
  { label: "Archie Comics", id: "32" },
  { label: "Viz Media", id: "27" },
  { label: "Kodansha", id: "5493" },
  { label: "Humanoids", id: "147" },
  { label: "Fantagraphics", id: "64" },
  { label: "Zenescope", id: "2244" },
  { label: "Ablaze", id: "8886" },
  { label: "Vault Comics", id: "7656" },
  { label: "Black Mask", id: "4995" },
  { label: "Ahoy Comics", id: "8203" },
  { label: "Europe Comics", id: "6386" },
  { label: "Magnetic Press", id: "4883" },
  { label: "TKO Studios", id: "8336" },
  { label: "Mad Cave", id: "8071" },
  { label: "Source Point", id: "7320" },
  { label: "Scout Comics", id: "5174" },
  { label: "Heavy Metal", id: "232" },
  { label: "Rebellion", id: "228" },
  { label: "Icon Comics", id: "2600" },
  { label: "WildStorm", id: "16" },
  { label: "Mirage", id: "22" },
  { label: "Abstract Studio", id: "127" },
].sort((a, b) => a.label.localeCompare(b.label)); // Alphabetical order

